prompt -- Create tables --;
CREATE TABLE av_log
    (id                             NUMBER NOT NULL,
    avizo_id                       NUMBER(19,0),
    code                           NUMBER(19,0),
    msg                            VARCHAR2(255 CHAR))
/

ALTER TABLE av_log
ADD PRIMARY KEY (id)
USING INDEX
/

CREATE TABLE cr_ldap_group
    (id                             NUMBER(19,0) NOT NULL,
    version                        NUMBER(19,0) NOT NULL,
    created_by                     VARCHAR2(255 CHAR) NOT NULL,
    date_created                   TIMESTAMP (6) NOT NULL,
    last_updated                   TIMESTAMP (6) NOT NULL,
    ldap_group_key                 VARCHAR2(50 CHAR) NOT NULL,
    xrole_group                    NUMBER(19,0) NOT NULL,
    updated_by                     VARCHAR2(255 CHAR) NOT NULL)
/

ALTER TABLE cr_ldap_group
ADD PRIMARY KEY (id)
USING INDEX
/

CREATE TABLE crreqparws1
    (req_text                       VARCHAR2(2000 BYTE))
  NOPARALLEL
  LOGGING
  MONITORING
/

CREATE UNIQUE INDEX i_crreqparws1 ON crreqparws1
  (
    req_text                        ASC
  )
NOPARALLEL
LOGGING
/

CREATE TABLE sc_notif
    (id                             NUMBER(19,0) NOT NULL,
    version                        NUMBER(19,0) NOT NULL,
    body                           VARCHAR2(4000 CHAR) NOT NULL,
    created_by                     VARCHAR2(255 CHAR) NOT NULL,
    date_created                   TIMESTAMP (6) NOT NULL,
    errm                           VARCHAR2(1000 CHAR),
    event_id                       VARCHAR2(50 CHAR),
    last_updated                   TIMESTAMP (6) NOT NULL,
    notif_sended                   TIMESTAMP (6),
    recipients                     VARCHAR2(1000 CHAR),
    req_avizo_id                   NUMBER(19,0) NOT NULL,
    sender                         VARCHAR2(100 CHAR) NOT NULL,
    status                         NUMBER(10,0) NOT NULL,
    subject                        VARCHAR2(1000 CHAR) NOT NULL,
    updated_by                     VARCHAR2(255 CHAR) NOT NULL)
/

ALTER TABLE sc_notif
ADD PRIMARY KEY (id)
USING INDEX
/

ALTER TABLE sc_notif
ADD CONSTRAINT uk_ors5mvfjqsh7aervfxf25j3n6 UNIQUE (req_avizo_id)
USING INDEX
/

CREATE TABLE sc_notifev
    (id                             VARCHAR2(50 CHAR) NOT NULL,
    version                        NUMBER(19,0) NOT NULL,
    created_by                     VARCHAR2(255 CHAR) NOT NULL,
    date_created                   TIMESTAMP (6) NOT NULL,
    description                    VARCHAR2(255 CHAR) NOT NULL,
    last_updated                   TIMESTAMP (6) NOT NULL,
    updated_by                     VARCHAR2(255 CHAR) NOT NULL)
/

ALTER TABLE sc_notifev
ADD PRIMARY KEY (id)
USING INDEX
/

CREATE TABLE sc_notiftmp
    (id                             NUMBER(19,0) NOT NULL,
    version                        NUMBER(19,0) NOT NULL,
    clazz                          VARCHAR2(255 CHAR),
    created_by                     VARCHAR2(255 CHAR) NOT NULL,
    date_created                   TIMESTAMP (6) NOT NULL,
    event_id                       VARCHAR2(50 CHAR),
    is_body                        NUMBER(1,0),
    last_updated                   TIMESTAMP (6) NOT NULL,
    object_props                   VARCHAR2(2000 CHAR),
    template_text                  VARCHAR2(2000 CHAR),
    updated_by                     VARCHAR2(255 CHAR) NOT NULL,
    template_part                  NUMBER(10,0) NOT NULL)
/

ALTER TABLE sc_notiftmp
ADD PRIMARY KEY (id)
USING INDEX
/

ALTER TABLE av_log
ADD CONSTRAINT fk_qcubck1n7vbfbxifs6f4c9xl8 FOREIGN KEY (avizo_id)
REFERENCES cravizo (id)
/
ALTER TABLE cr_ldap_group
ADD CONSTRAINT fk_6cygmb4xhsyhnwchhyo7lftxf FOREIGN KEY (xrole_group)
REFERENCES sc_role_group (id)
/
ALTER TABLE sc_notif
ADD CONSTRAINT fk_ke5fo1fnqnafbrxrt7hg17d4j FOREIGN KEY (event_id)
REFERENCES sc_notifev (id)
/
ALTER TABLE sc_notif
ADD CONSTRAINT fk_ors5mvfjqsh7aervfxf25j3n6 FOREIGN KEY (req_avizo_id)
REFERENCES av_reqavizo (id)
/
ALTER TABLE sc_notiftmp
ADD CONSTRAINT fk_stqmriatueoboush29dsx21e3 FOREIGN KEY (event_id)
REFERENCES sc_notifev (id)
/

CREATE TABLE sc_notiftmp
    (id                             NUMBER(19,0) NOT NULL,
    version                        NUMBER(19,0) NOT NULL,
    clazz                          VARCHAR2(255 CHAR),
    created_by                     VARCHAR2(255 CHAR) NOT NULL,
    date_created                   TIMESTAMP (6) NOT NULL,
    event_id                       VARCHAR2(50 CHAR),
    is_body                        NUMBER(1,0),
    last_updated                   TIMESTAMP (6) NOT NULL,
    object_props                   VARCHAR2(2000 CHAR),
    template_text                  VARCHAR2(2000 CHAR),
    updated_by                     VARCHAR2(255 CHAR) NOT NULL,
    template_part                  NUMBER(10,0) NOT NULL)
/

ALTER TABLE sc_notiftmp
ADD PRIMARY KEY (id)
USING INDEX
/

ALTER TABLE sc_notiftmp
ADD CONSTRAINT fk_stqmriatueoboush29dsx21e3 FOREIGN KEY (event_id)
REFERENCES sc_notifev (id)
/

prompt -- create quartz --;
CREATE TABLE qrtz_job_details
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL, 
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);
CREATE TABLE qrtz_triggers
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL, 
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(13) NULL,
    PREV_FIRE_TIME NUMBER(13) NULL,
    PRIORITY NUMBER(13) NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER(2) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) 
    REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP) 
);
CREATE TABLE qrtz_simple_triggers
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);
CREATE TABLE qrtz_cron_triggers
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);
CREATE TABLE qrtz_simprop_triggers
  (          
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 NUMBER(10) NULL,
    INT_PROP_2 NUMBER(10) NULL,
    LONG_PROP_1 NUMBER(13) NULL,
    LONG_PROP_2 NUMBER(13) NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 VARCHAR(1) NULL,
    BOOL_PROP_2 VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);
CREATE TABLE qrtz_blob_triggers
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);
CREATE TABLE qrtz_calendars
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME  VARCHAR2(200) NOT NULL, 
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);
CREATE TABLE qrtz_paused_trigger_grps
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);
CREATE TABLE qrtz_fired_triggers 
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(13) NOT NULL,
    SCHED_TIME NUMBER(13,0) NOT NULL,
    PRIORITY NUMBER(13) NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_NONCONCURRENT VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);
CREATE TABLE qrtz_scheduler_state 
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL NUMBER(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);
CREATE TABLE qrtz_locks
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR2(40) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);

create index idx_qrtz_j_req_recovery on qrtz_job_details(SCHED_NAME,REQUESTS_RECOVERY);
create index idx_qrtz_j_grp on qrtz_job_details(SCHED_NAME,JOB_GROUP);

create index idx_qrtz_t_j on qrtz_triggers(SCHED_NAME,JOB_NAME,JOB_GROUP);
create index idx_qrtz_t_jg on qrtz_triggers(SCHED_NAME,JOB_GROUP);
create index idx_qrtz_t_c on qrtz_triggers(SCHED_NAME,CALENDAR_NAME);
create index idx_qrtz_t_g on qrtz_triggers(SCHED_NAME,TRIGGER_GROUP);
create index idx_qrtz_t_state on qrtz_triggers(SCHED_NAME,TRIGGER_STATE);
create index idx_qrtz_t_n_state on qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
create index idx_qrtz_t_n_g_state on qrtz_triggers(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE);
create index idx_qrtz_t_next_fire_time on qrtz_triggers(SCHED_NAME,NEXT_FIRE_TIME);
create index idx_qrtz_t_nft_st on qrtz_triggers(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
create index idx_qrtz_t_nft_misfire on qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
create index idx_qrtz_t_nft_st_misfire on qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
create index idx_qrtz_t_nft_st_misfire_grp on qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

create index idx_qrtz_ft_trig_inst_name on qrtz_fired_triggers(SCHED_NAME,INSTANCE_NAME);
create index idx_qrtz_ft_inst_job_req_rcvry on qrtz_fired_triggers(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
create index idx_qrtz_ft_j_g on qrtz_fired_triggers(SCHED_NAME,JOB_NAME,JOB_GROUP);
create index idx_qrtz_ft_jg on qrtz_fired_triggers(SCHED_NAME,JOB_GROUP);
create index idx_qrtz_ft_t_g on qrtz_fired_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
create index idx_qrtz_ft_tg on qrtz_fired_triggers(SCHED_NAME,TRIGGER_GROUP);
commit;

prompt -- Add collumns --;
ALTER TABLE AV_CROSOBA ADD ( ATR_BIFO_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_DTNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_DTUMR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_IC_ID NUMBER (19) )
/
ALTER TABLE AV_CRMENO ADD ( ATR_MENO_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_MNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_MUMR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_NARODNOST_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_OKRNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_OKRUMR_ID NUMBER (19) )
/
ALTER TABLE AV_CRPOBYT ADD ( ATR_POBYT_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_POHL_ID NUMBER (19) )
/
ALTER TABLE AV_CRPRIEZ ADD ( ATR_PRIEZVISKO_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_RC_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_RODMATR_ID NUMBER (19) )
/
ALTER TABLE AV_CRPRROD ADD ( ATR_RODPR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_RODST_ID NUMBER (19) )
/
ALTER TABLE AV_CRRODVZ ADD ( ATR_RODVZ_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_ROKNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_STNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CRUSSTOB ADD ( ATR_STOB_ID NUMBER (19) )
/
ALTER TABLE AV_CRSTPR ADD ( ATR_STPRISL_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_STUMR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_STZVEREJ_ID NUMBER (19) )
/
ALTER TABLE AV_CRTITOS ADD ( ATR_TITUL_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_TYPOSO_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_UCNAR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_UCUMR_ID NUMBER (19) )
/
ALTER TABLE AV_CROSOBA ADD ( ATR_UMRMATR_ID NUMBER (19) )
/
ALTER TABLE CRAVIZOATTROS ADD ( ERR_MSG VARCHAR2(255) )
/
ALTER TABLE AV_CRPOBYT ADD ( IDMV NUMBER (10) )
/
ALTER TABLE AV_CRRODVZ ADD ( IDMV NUMBER (10) )
/
ALTER TABLE CRPOBYT ADD ( IDMV NUMBER (10) )
/
ALTER TABLE AV_REQAVIZO ADD ( NOTIF_STATUS NUMBER (10) )
/
alter table AV_REQAVIZO modify(respmsg varchar2(4000))
/
ALTER TABLE AV_CRMENO ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CROSOBA ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRPOBYT ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRPRIEZ ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRPRROD ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRRODVZ ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRSTPR ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRTITOS ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRUSSTOB ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE CRAVIZO ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE CRAVIZOATTROS ADD ( VERSION NUMBER (19) NOT NULL )
/
ALTER TABLE AV_CRSTPR ADD ( FG_SR NUMBER (1) )
/
prompt -- Add Constraints --;
ALTER TABLE SC_NOTIFTMP   
ADD CONSTRAINT FK_STQMRIATUEOBOUSH29DSX21E3   
FOREIGN KEY (EVENT_ID)   
REFERENCES SC_NOTIFEV (ID);   
     
ALTER TABLE QRTZ_TRIGGERS   
ADD FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP);   
     
ALTER TABLE QRTZ_SIMPLE_TRIGGERS   
ADD FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);   
     
ALTER TABLE QRTZ_CRON_TRIGGERS   
ADD FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);   
     
ALTER TABLE QRTZ_SIMPROP_TRIGGERS   
ADD FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);   
     
ALTER TABLE QRTZ_BLOB_TRIGGERS   
ADD FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);   
     
ALTER TABLE CR_LDAP_GROUP   
ADD CONSTRAINT FK_6CYGMB4XHSYHNWCHHYO7LFTXF   
FOREIGN KEY (XROLE_GROUP)   
REFERENCES SC_ROLE_GROUP (ID);   
     
ALTER TABLE AV_LOG   
ADD CONSTRAINT FK_QCUBCK1N7VBFBXIFS6F4C9XL8   
FOREIGN KEY (AVIZO_ID)   
REFERENCES CRAVIZO (ID);   
     
ALTER TABLE SC_NOTIF   
ADD CONSTRAINT FK_KE5FO1FNQNAFBRXRT7HG17D4J   
FOREIGN KEY (EVENT_ID)   
REFERENCES SC_NOTIFEV (ID);   
     
ALTER TABLE SC_NOTIF   
ADD CONSTRAINT FK_ORS5MVFJQSH7AERVFXF25J3N6   
FOREIGN KEY (REQ_AVIZO_ID)   
REFERENCES AV_REQAVIZO (ID);   
     
ALTER TABLE CREVOS   
ADD CONSTRAINT FK_1LHHDAOGU0M2R4MO7WKX8LGLL   
FOREIGN KEY (CROSOBA)   
REFERENCES CROSOBA (ID);   
     
ALTER TABLE CRREQUEST   
ADD CONSTRAINT FK_53CF54NF8KP56C75AJFLJHY8T   
FOREIGN KEY (AVIZO_ID)   
REFERENCES CRAVIZO (ID);   
     
ALTER TABLE CRREQPAR   
ADD CONSTRAINT FK_FF8Y1BWPF92W2COP332XU45R0   
FOREIGN KEY (REQID)   
REFERENCES CRREQUEST (ID);   
     
ALTER TABLE AV_REQAVIZO   
ADD CONSTRAINT FK_P21Q8OUUHXNL1LWWXVDOQ8AEW   
FOREIGN KEY (AVIZO_ID)   
REFERENCES CRAVIZO (ID);   
     
ALTER TABLE AV_REQAVIZO   
ADD CONSTRAINT FK_RHN1OS5A4XDIGYQEAQX6T5NV6   
FOREIGN KEY (REQID)   
REFERENCES CRREQUEST (ID);   
     
ALTER TABLE AV_CRMENO   
ADD CONSTRAINT FK_9P3IRWUHGWQ2VAVFRIJNUY454   
FOREIGN KEY (ATR_MENO_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_KRLA0NO7WEA1U2XT31IGMKYGX   
FOREIGN KEY (ATR_BIFO_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_KE32YKDRB0CYDKEQ4URG1DMA1   
FOREIGN KEY (ATR_DTNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_98XX7CGX5EXBRV9N2K0GON3QH   
FOREIGN KEY (ATR_DTUMR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_LLEB3K9DA7YYLY70SF3EAQ97C   
FOREIGN KEY (ATR_IC_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_498MVBNX6U0OSB5LR1AU3RXXO   
FOREIGN KEY (ATR_MUMR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_RAITARXCU9BLSX9FUXHWR70P0   
FOREIGN KEY (ATR_MNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_S79B2DK8DG348JRKJC1TO8PCO   
FOREIGN KEY (ATR_NARODNOST_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_GQ631IWJ0U2EQ4KWR6IVSNC7R   
FOREIGN KEY (ATR_OKRNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_LY8VMB0O5MALGMBUHX07C0GUC   
FOREIGN KEY (ATR_OKRUMR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_AVU5I3HHJHJF0LFYY20XLWVPI   
FOREIGN KEY (ATR_RC_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_EFG0KHBQR7UN45D5CTRASWCC5   
FOREIGN KEY (ATR_RODMATR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_9HXJ57KCGLMIG7KTA9T1N0ASR   
FOREIGN KEY (ATR_RODST_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_2G5UOF572STQXLCF04SXXMMR   
FOREIGN KEY (ATR_ROKNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_AKV15CCXJIHSGJ6S9VMY8TXI2   
FOREIGN KEY (ATR_STNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_9FQKPRQAX8HP009WJ0SM0UNBJ   
FOREIGN KEY (ATR_STUMR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_8WBVRXYH31U63CQHCWP8KIT1O   
FOREIGN KEY (ATR_STZVEREJ_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_62H75YU4IGTWJH77UQ78BL0Q6   
FOREIGN KEY (ATR_TYPOSO_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_H34H2XOKNWS7P2WFOWYJS379   
FOREIGN KEY (ATR_UCNAR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_DLOW3OLJ06KXRAG04M0H3Q0JG   
FOREIGN KEY (ATR_UCUMR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_8F8XY009K79YSGA335VWMWO1W   
FOREIGN KEY (ATR_UMRMATR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CROSOBA   
ADD CONSTRAINT FK_FRF177PAYLU6UE1H41VBKBKIO   
FOREIGN KEY (ATR_POHL_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRPOBYT   
ADD CONSTRAINT FK_HT7BH286EM8MT1EWVRSDW8XQV   
FOREIGN KEY (ATR_POBYT_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRPRIEZ   
ADD CONSTRAINT FK_FNF16UJIAQTNY4F8IX3RUB9RF   
FOREIGN KEY (ATR_PRIEZVISKO_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRPRROD   
ADD CONSTRAINT FK_GIT29RDXHEJAEWMP04BJ0OTFD   
FOREIGN KEY (ATR_RODPR_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRRODVZ   
ADD CONSTRAINT FK_2NSANKSPDYQKVCTCDYLVRMRUA   
FOREIGN KEY (ATR_RODVZ_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRSTPR   
ADD CONSTRAINT FK_5T725YNX2T20Y4DDD34M1CQWF   
FOREIGN KEY (ATR_STPRISL_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRTITOS   
ADD CONSTRAINT FK_JDEBGYY4U6EK2L6T1K3CXC9VP   
FOREIGN KEY (ATR_TITUL_ID)   
REFERENCES CRAVIZOATTROS (ID);   
     
ALTER TABLE AV_CRUSSTOB   
ADD CONSTRAINT FK_IQWFXWA0O61DCPSN9Y0R244SK   
FOREIGN KEY (ATR_STOB_ID)   
REFERENCES CRAVIZOATTROS (ID);   

Prompt Sequence SC_NOTIFTMP_SEQ;
CREATE SEQUENCE SC_NOTIFTMP_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  GLOBAL;


Prompt Sequence SC_NOTIF_SEQ;
CREATE SEQUENCE SC_NOTIF_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  GLOBAL;
