ALTER TABLE AV_CRMENO 
RENAME COLUMN ATR_MENO_ID TO AVATR_ID
/
ALTER TABLE AV_CRPOBYT 
RENAME COLUMN ATR_POBYT_ID TO AVATR_ID
/
ALTER TABLE AV_CRPRIEZ 
RENAME COLUMN ATR_PRIEZVISKO_ID TO AVATR_ID
/
ALTER TABLE AV_CRPRROD 
RENAME COLUMN ATR_RODPR_ID TO AVATR_ID
/
ALTER TABLE AV_CRPRSPOS 
RENAME COLUMN ATR_OBM_ST_PR_ID TO AVATR_ID
/
ALTER TABLE AV_CRRODVZ 
RENAME COLUMN ATR_RODVZ_ID TO AVATR_ID
/
ALTER TABLE AV_CRSTPR 
RENAME COLUMN ATR_STPRISL_ID TO AVATR_ID
/
ALTER TABLE AV_CRTITOS 
RENAME COLUMN ATR_TITUL_ID TO AVATR_ID
/
ALTER TABLE AV_CRUSSTOB 
RENAME COLUMN ATR_STOB_ID TO AVATR_ID
/
ALTER TABLE AV_CRZRMR 
RENAME COLUMN ATR_VYHL_MRTVY_ID TO AVATR_ID
/