isc.ClassFactory.defineClass("HomeComp","VLayout").addProperties({height:"100%",width:"100%",padding:2,thisTab:null,initWidget:function(){this.Super("initWidget",arguments);var a=this;if(App.get.user.hasAnyRole("ROLE_AVREAD"))this.thisTab.name="OsobaView",App.getDataSource("OsobaView",function(c){c&&(a.mainGrid=isc.GridComponentAny.create({dataSource:c,tabSet:appTabSet,type:"normal",_myTabName:a.thisTab.name,getDetail:function(){if(this.grid.getSelectedRecord()){var a=this.dataSource.getPrimaryKeyFieldName(),
a=this.grid.getSelectedRecord()[a];App._showDetailByPK(this.dataSource,a,appTabSet,this.type,this.brefField,this.brefValue,this._ownerComp,this)}}}),a.mainGrid.toolBar._btnCancel.hide(),a.addMember(a.mainGrid))});else{this._sectionStack=isc.SectionStack.create({height:"100%",width:"100%",overflow:"auto",visibilityMode:"multiple"});this.addMember(this._sectionStack);var b=isc.HTMLPane.create({height:"100%",contents:"<table style='font-size:16; border-bottom:1px solid black;width:100%;height:20px;'><tr><td><b>Expression Filter</b></td></tr></table><br><table style='font-size:14;height:100%;;max-height:200px;'><tr><td style='border-bottom:1px solid black;'><b>Prefix</b></td><td style='border-bottom:1px solid black;'><b>Operator</b></td></tr><tr><td>&lt;</td><td>"+
isc.i18nMessages.operators_lessThanTitle+"</td></tr><tr><td>&gt;</td><td>"+isc.i18nMessages.operators_greaterThanTitle+"</td></tr><tr><td>&lt;=</td><td>"+isc.i18nMessages.operators_lessOrEqualTitle+"</td></tr><tr><td>&gt;=</td><td>"+isc.i18nMessages.operators_greaterOrEqualTitle+"</td></tr><tr><td>someValue...someValue</td><td>"+isc.i18nMessages.operators_iBetweenInclusiveTitle+"</td></tr><tr><td>!</td><td>"+isc.i18nMessages.operators_notEqualTitle+"</td></tr><tr><td>^</td><td>"+isc.i18nMessages.operators_startsWithTitle+
"</td></tr><tr><td>|</td><td>"+isc.i18nMessages.operators_endsWithTitle+"</td></tr><tr><td>!^</td><td>"+isc.i18nMessages.operators_notStartsWithTitle+"</td></tr><tr><td>!@</td><td>"+isc.i18nMessages.operators_notEndsWithTitle+"</td></tr><tr><td>~</td><td>"+isc.i18nMessages.operators_containsTitle+"</td></tr><tr><td>!~</td><td>"+isc.i18nMessages.operators_notContainsTitle+"</td></tr><tr><td>=(value1|value2)</td><td>"+isc.i18nMessages.operators_inSetTitle+"</td></tr><tr><td>!=(value1|value2)</td><td>"+
isc.i18nMessages.operators_notInSetTitle+"</td></tr><tr><td>#</td><td>"+isc.i18nMessages.operators_isNullTitle+"</td></tr><tr><td>!#</td><td>"+isc.i18nMessages.operators_notNullTitle+"</td></tr><tr><td>==</td><td>"+isc.i18nMessages.operators_equalsTitle+"</td></tr><tr><td>=.</td><td>"+isc.i18nMessages.operators_equalsFieldTitle+"</td></tr></table>"}),e=isc.HTMLPane.create({height:"100%",contents:"<table style='font-size:16; border-bottom:1px solid black;width:100%;height:20px;'><tr><td><b>"+isc.i18nMessages["smartsfs.help.shortkeys"]+
"</b></td></tr></table><br><table style='font-size:14;height:100%;max-height:180px;'><tr><td style='border-bottom:1px solid black;'><b>"+isc.i18nMessages["smartsfs.help.shortkey"]+"</b></td><td style='border-bottom:1px solid black;'><b>"+isc.i18nMessages["smartsfs.help.shortkeyAction"]+"</b></td></tr><tr><td>F2 / Ctrl+A</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF2"]+"</td></tr><tr><td>F3 / Ctrl+S</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF3"]+"</td></tr><tr><td>F4 / Ctrl+F</td><td>"+
isc.i18nMessages["smartsfs.help.shortkeyF4"]+"</td></tr><tr><td>F5 / Ctrl+R</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF5"]+"</td></tr><tr><td>F6 / Ctrl+E</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF6"]+"</td></tr><tr><td>F7 / Ctrl+I</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF7"]+"</td></tr><tr><td>F8 / Ctrl+E</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF8"]+"</td></tr><tr><td>F9 / Ctrl+P</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyF9"]+"</td></tr><tr><td>F10</td><td>"+
isc.i18nMessages["smartsfs.help.shortkeyF10"]+"</td></tr><tr><td>Esc / Ctrl+Q</td><td>"+isc.i18nMessages["smartsfs.help.shortkeyEsc"]+"</td></tr></table>"}),d=isc.HLayout.create({height:"100%",width:"100%"});d.addMember(b);d.addMember(e);b=isc.HTMLPane.create({height:200,contentsURL:App.appRootUrl+"/services"});a._sectionStack.addSection({name:"section_help",title:isc.i18nMessages["smartcrfo.help.title"],expanded:!1,resizeable:!0,items:[d]});a._sectionStack.addSection({name:"section_main",title:isc.i18nMessages["smartcrfo.services.title"],
expanded:!0,resizeable:!0,items:[b]});App.getDataSource("HotNews",function(c){if(c){var b=new Date;a.homeNews=isc.ListGrid.create({ID:"hotNews",height:"100%",width:"100%",dataSource:c,initialCriteria:{_constructor:"AdvancedCriteria",operator:"and",criteria:[{fieldName:"startDate",operator:"lessOrEqual",value:b},{operator:"or",criteria:[{fieldName:"endDate",operator:"greaterOrEqual",value:b},{fieldName:"endDate",operator:"isNull"}]}]},refresh:function(){this.invalidateCache();this.delayCall("refresh",
[],6E5)},type:"normal",showHeader:!1,autoFetchData:!0,fields:[{name:"messageText",title:"messageText"},{name:"startDate",title:"startDate"}],wrapCells:!0,fixedRecordHeights:!1,initialSort:[{property:"startDate",direction:"descending"},{property:"priority",direction:"ascending"}],hilites:[{fieldName:"messageText",cssText:"color:#0000CC;",criteria:{fieldName:"priority",operator:"equals",value:"MEDIUM"}},{fieldName:"messageText",cssText:"color:#FF0000;",criteria:{fieldName:"priority",operator:"equals",
value:"HIGH"}}]});a._sectionStack.addSection({name:"section_news",title:isc.i18nMessages["smartekom.homenews.title"],expanded:!0,resizeable:!0,items:[a.homeNews]});a.homeNews.delayCall("refresh",[],6E5)}})}appTabSet.setTabPane(this.thisTab,a)}});
