isc.ClassFactory.defineClass("XMLBeauty").addProperties({step:"   ",shift:[],createShiftArr:function(e){var d="    ";if(isNaN(parseInt(e)))d=e;else switch(e){case 1:d=" ";break;case 2:d="  ";break;case 3:d="   ";break;case 4:d="    ";break;case 5:d="     ";break;case 6:d="      ";break;case 7:d="       ";break;case 8:d="        ";break;case 9:d="         ";break;case 10:d="          ";break;case 11:d="           ";break;case 12:d="            "}e=["\n"];for(ix=0;100>ix;ix++)e.push(e[ix]+d);return e},
init:function(){this.step="   ";this.shift=this.createShiftArr(this.step)},parseXml:function(e,d){for(var a=e.replace(/>\s{0,}</g,"><").replace(/</g,"~::~<").replace(/\s*xmlns\:/g,"~::~xmlns:").replace(/\s*xmlns\=/g,"~::~xmlns=").split("~::~"),h=a.length,g=!1,f=0,c="",b=0,k=d?this.createShiftArr(d):this.shift,b=0;b<h;b++)if(-1<a[b].search(/<!/)){if(c+=k[f]+a[b],g=!0,-1<a[b].search(/--\x3e/)||-1<a[b].search(/\]>/)||-1<a[b].search(/!DOCTYPE/))g=!1}else-1<a[b].search(/--\x3e/)||-1<a[b].search(/\]>/)?
(c+=a[b],g=!1):/^<\w/.exec(a[b-1])&&/^<\/\w/.exec(a[b])&&/^<[\w:\-\.\,]+/.exec(a[b-1])==/^<\/[\w:\-\.\,]+/.exec(a[b])[0].replace("/","")?(c+=a[b],g||f--):c=-1<a[b].search(/<\w/)&&-1==a[b].search(/<\//)&&-1==a[b].search(/\/>/)?g?c+=a[b]:c+=k[f++]+a[b]:-1<a[b].search(/<\w/)&&-1<a[b].search(/<\//)?g?c+=a[b]:c+=k[f]+a[b]:-1<a[b].search(/<\//)?g?c+=a[b]:c+=k[--f]+a[b]:-1<a[b].search(/\/>/)?g?c+=a[b]:c+=k[f]+a[b]:-1<a[b].search(/<\?/)?c+(k[f]+a[b]):-1<a[b].search(/xmlns\:/)||-1<a[b].search(/xmlns\=/)?c+
(k[f]+a[b]):c+a[b];return"\n"==c[0]?c.slice(1):c}});
isc.ClassFactory.defineClass("WSTest").addClassProperties({wsProps:[{name:"ws1",wsoper:"ws1OverenieRegistracie",wsresp:"ws1OverenieRegistracieResponse",title:"requestLog.ws1",icon:"[SKIN]/custom/world.png"},{name:"ws1recall",wsoper:"ws1RecallRequest",wsresp:"ws1RecallRequestResponse",title:"requestLog.ws1recall",icon:"[SKIN]/custom/world.png"},{name:"ws2ifo",wsoper:"ws2AktualizaciaFOByIFO",wsresp:"ws2AktualizaciaFOByIFOResponse",title:"requestLog.ws2ifo",icon:"[SKIN]/custom/world.png"},{name:"ws2rc",
wsoper:"ws2AktualizaciaFOByRC",wsresp:"ws2AktualizaciaFOByRCResponse",title:"requestLog.ws2",icon:"[SKIN]/custom/world.png"},{name:"ws2recall",wsoper:"ws2RecallRequest",wsresp:"ws2RecallRequestResponse",title:"requestLog.ws2recall",icon:"[SKIN]/custom/world.png"},{name:"ws3",wsoper:"ws3ZmenySkupUdajov",wsresp:"ws3ZmenySkupUdajovResponse",title:"requestLog.ws3",icon:"[SKIN]/custom/world.png"},{name:"ws4",wsoper:"ws4ZaujemFO",wsresp:"ws4ZaujemFOResponse",title:"requestLog.ws4",icon:"[SKIN]/custom/world.png"},
{name:"ws4recall",wsoper:"ws4RecallRequest",wsresp:"ws4RecallRequestResponse",title:"requestLog.ws4recall",icon:"[SKIN]/custom/world.png"},{name:"ws6",wsoper:"ws6NovoNarodeneDeti",wsresp:"ws6NovoNarodeneDetiResponse",title:"requestLog.ws6",icon:"[SKIN]/custom/world.png"}],service:null,wsName:null,params:null}).addProperties({loadWS:function(e){var d=this;null==d.service&&isc.XMLTools.loadWSDL(App.appRootUrl+"/services/crfoWSA?wsdl",function(a){d.service=a;isA.Function(e)&&e()},null,!0)},sendWS:function(e,
d){var a=this;a.dialog&&a.dialog.isA("Window")&&a.dialog.destroy();if(a.service){e||(e=a.wsName,d=a.params);var h=WSTest.wsProps.find({name:e});a.parentDataComp=d.dataComp;a.inputDS=a.service.getInputDS(h.wsoper);console.log(a.inputDS);a.inputForm=isc.DynamicForm.create({validateOnExit:!0,width:"100%",border:"1px solid blue",padding:20,dataSource:a.inputDS,canEdit:!0,wrapItemTitles:!1,autoFocus:!0});for(var g=a.inputForm.getFields(),f=[],c=0;c<g.length;c++){var b=g[c];prop={name:b.name,type:b.type,
title:isc.i18nMessages["requestLog."+h.name+"."+b.name+".label"],valuesMap:b.valuesMap};f.add(prop);b.destroy()}f.add({name:"spacer",editorType:"RowSpacerItem"});f.add({name:"executeBtn",type:"button",canFocus:!0,colSpan:2,canEdit:null,title:isc.i18nMessages[h.title],autoFit:!0,showButtonTitle:!0,icon:h.icon,click:function(){this.form.validate()&&a.service.callOperation(h.wsoper,a.inputForm.getValues(),h.wsresp,function(b,c,d,e){b=XMLBeauty.create().parseXml(isc.XMLTools.serializeToString(c));a.inputForm.setValue("result",
b);a.inputForm.items.find({name:"result"}).show();a.inputForm.markForRedraw();a.parentDataComp.reload()},{xmlResult:!0})}});f.add({name:"rspace",editorType:"RowSpacerItem"});f.add({name:"result",colSpan:3,endRow:!0,startRow:!0,length:5E4,title:isc.i18nMessages["requestLog.wstest.result.label"],titleOrientation:"top",type:"text",width:900,minHeight:250,maxHeight:500,wrap:"OFF",visible:!1});a.inputForm.removeFields(g);a.inputForm.setFields(f);a.dialog=isc.Window.create({width:300,isModal:!0,headerIconProperties:{src:h.icon},
showModalMask:!0,autoCenter:!0,autoSize:!0,canDragResize:!0,showFooter:!0,showMinimizeButton:!1,canDragReposition:!0,canDragResize:!0,title:isc.i18nMessages[h.title],items:[a.inputForm],autoDraw:!0})}else e&&(a.wsName=e,a.params=d),a.loadWS(a.sendWS)}});
