SET DEFINE OFF;
MERGE INTO SC_MENUITEM A USING
 (SELECT
  0 as ID,
  0 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,462000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('28.10.2015 17:44:01,462000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  NULL as XITEM,
  'menu.configuration.title' as TITLE,
  'unknown' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  1 as ID,
  0 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,490000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'MenuItem' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('28.10.2015 17:44:01,490000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  0 as XITEM,
  'menu.menuItem.title' as TITLE,
  'unknown' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  2 as ID,
  0 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,500000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'SmartSource' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('28.10.2015 17:44:01,500000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  0 as XITEM,
  'menu.dataSource.title' as TITLE,
  'unknown' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  3 as ID,
  0 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,509000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RequestMap' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('28.10.2015 17:44:01,509000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  0 as XITEM,
  'menu.requestMap.title' as TITLE,
  'unknown' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  4 as ID,
  2 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,516000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('19.12.2018 12:27:17,314000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER,ROLE_AVADM' as NEEDROLE,
  NULL as XITEM,
  'menu.administration.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  5 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,524000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'Localization' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('3.11.2015 16:20:25,872000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  4 as XITEM,
  'menu.localization.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  6 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,531000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'LocaleLang' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('3.11.2015 16:20:34,687000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  4 as XITEM,
  'menu.localeLang.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  7 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,539000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'LocaleCountry' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('3.11.2015 16:20:42,685000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  4 as XITEM,
  'menu.localeCountry.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  8 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,548000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'ConfigProperty' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('3.11.2015 16:20:50,861000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  4 as XITEM,
  'menu.configProperty.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  9 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,554000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('30.11.2018 10:09:50,054000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  NULL as XITEM,
  'menu.appSecurity.title' as TITLE,
  'adminLdap' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  10 as ID,
  5 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,561000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'Uzivatel' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('6.12.2018 19:20:00,698000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_SUPER' as NEEDROLE,
  9 as XITEM,
  'menu.user.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  11 as ID,
  1 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,568000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'Role' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('3.11.2015 16:21:05,607000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  9 as XITEM,
  'menu.roles.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  12 as ID,
  3 as VERSION,
  'unknown' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 17:44:01,576000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RoleGroup' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 12:01:39,765000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_SUPER' as NEEDROLE,
  9 as XITEM,
  'menu.roleGroups.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  13 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 19:08:14,272000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('6.12.2018 19:17:50,335000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  NULL as XITEM,
  'menu.ciselniky.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  14 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('28.10.2015 19:08:47,040000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'SystemCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('28.10.2015 19:08:47,040000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.systemCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  17 as ID,
  5 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('2.11.2015 14:12:43,842000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('14.1.2019 9:14:13,041000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_CRFOAPP' as NEEDROLE,
  NULL as XITEM,
  'menu.spravacrfo.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  18 as ID,
  5 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('2.11.2015 14:13:36,327000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'OsobaView' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('14.1.2019 9:14:30,189000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_CRFOAPP' as NEEDROLE,
  17 as XITEM,
  'menu.osobaview.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  19 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('5.11.2015 12:49:21,262000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RequestLog' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('14.1.2019 9:14:37,010000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_CRFOAPP' as NEEDROLE,
  17 as XITEM,
  'menu.requestLog.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  20 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('5.11.2015 15:05:55,727000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'EventLog' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('14.1.2019 9:14:47,430000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN' as NEEDROLE,
  17 as XITEM,
  'menu.eventLog.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  21 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:15,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'DruhDokladuCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:15,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.DruhDokladuCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  22 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'KodOpovedeCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.KodOpovedeCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  23 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'NarodnostCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.NarodnostCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  24 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'PohlavieCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.PohlavieCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  25 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RodinnyStavCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.RodinnyStavCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  26 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'SkupUdajovCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.SkupUdajovCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  27 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'StatCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.StatCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  28 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'StupenZverejCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.StupenZverejCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  29 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TitulCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TitulCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  30 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypTitulCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypTitulCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  31 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypObmSposCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypObmSposCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  32 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypOsobyCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypOsobyCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  33 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypPobytuCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypPobytuCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  34 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypRoleVztCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypRoleVztCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  35 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypUzCelokCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypUzCelokCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  36 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'TypVztahCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.TypVztahCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  37 as ID,
  0 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'UzemnyCelokCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('12.11.2015 12:29:16,000000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  13 as XITEM,
  'menu.UzemnyCelokCis.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  38 as ID,
  1 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('13.11.2015 16:14:10,749000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RequestParamCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.12.2018 12:10:08,600000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  13 as XITEM,
  'menu.RequestParamCis.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  39 as ID,
  1 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('21.1.2016 9:31:53,529000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'HotNews' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('21.1.2016 13:54:14,439000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  4 as XITEM,
  'menu.hotNews.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  40 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('16.8.2016 11:08:36,687000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'XsdSchemyCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.12.2018 12:10:16,321000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  13 as XITEM,
  'xsdSchemyCis.plural.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  41 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('25.5.2017 12:05:23,610000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RequestNND' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('1.6.2017 7:07:10,138000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER,ROLE_ADMIN' as NEEDROLE,
  17 as XITEM,
  'menu.requestnnd.title' as TITLE,
  'admin' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  42 as ID,
  0 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('3.12.2018 20:37:23,452000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'LdapGroup' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('3.12.2018 20:37:23,452000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  9 as XITEM,
  'menu.ldapGroup.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  44 as ID,
  4 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('29.9.2017 9:32:05,555000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'AvizVybavCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.12.2018 12:10:23,968000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  13 as XITEM,
  'Parametre 412' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  50 as ID,
  2 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('4.12.2018 10:30:48,305000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('10.12.2018 9:59:17,922000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  NULL as XITEM,
  'Register adries' as TITLE,
  'adminLdap' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  51 as ID,
  3 as VERSION,
  'admin' as CREATED_BY,
  TO_TIMESTAMP('4.12.2018 10:32:08,040000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RegUlicaCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.1.2019 13:00:48,085000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  50 as XITEM,
  'regUlicaCis.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  52 as ID,
  3 as VERSION,
  'adminLdap' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 9:53:39,319000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RegDomCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.1.2019 13:04:46,381000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  50 as XITEM,
  'regDomCis.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  53 as ID,
  2 as VERSION,
  'adminLdap' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 9:54:41,274000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'RegVchodDomuCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.1.2019 13:07:54,188000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  50 as XITEM,
  'regVchodDomuCis.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  54 as ID,
  1 as VERSION,
  'adminLdap' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 10:02:30,181000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as DATE_CREATED,
  'StavDomuCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.1.2019 13:09:27,825000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS,FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  50 as XITEM,
  'stavDomuCis.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  55 as ID,
  1 as VERSION,
  'adminLdap' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 10:04:46.235000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'StavDomVchodCis' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.1.2019 13:10:56.220000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_ADMIN,ROLE_AVADM' as NEEDROLE,
  50 as XITEM,
  'stavDomVchodCis.label' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  56 as ID,
  0 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('18.12.2018 11:40:08.726000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'RegUlicaObceView' as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 11:40:08.726000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_SUPER' as NEEDROLE,
  50 as XITEM,
  'Ulice obce' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  61 as ID,
  3 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('7.12.2018 15:32:14.827000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 10:20:03.804000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  NULL as XITEM,
  'menu.avizo.notifikacie' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  62 as ID,
  2 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('7.12.2018 15:33:54.106000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'NotifEventEnum' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 10:20:20.566000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  61 as XITEM,
  'menu.avizo.notifEvent' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  63 as ID,
  1 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 15:18:25.913000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'NotifTemplate' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 10:20:27.231000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  61 as XITEM,
  'menu.avizo.notifTemplate' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  69 as ID,
  2 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('10.12.2018 15:16:17.650000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'NotificationView' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('18.12.2018 10:20:34.129000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  61 as XITEM,
  'menu.avizo.notifikacieView' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  71 as ID,
  0 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('11.12.2018 13:36:39.033000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'Jobs' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('11.12.2018 13:36:39.033000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  4 as XITEM,
  'menu.jobs.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  81 as ID,
  0 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('17.12.2018 9:55:09.602000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  NULL as GRIDDS,
  NULL as ICON_CLS,
  1 as IS_OPEN,
  TO_TIMESTAMP('17.12.2018 9:55:09.602000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_APPAVIZO' as NEEDROLE,
  NULL as XITEM,
  'menu.aviza.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  82 as ID,
  0 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('17.12.2018 9:56:08.546000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'OsobaView' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('17.12.2018 9:56:08.546000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_APPAVIZO' as NEEDROLE,
  81 as XITEM,
  'menu.osobaview.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  83 as ID,
  1 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('17.12.2018 9:57:40.989000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'AvizoOsobaView' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('17.12.2018 9:57:52.900000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_APPAVIZO' as NEEDROLE,
  81 as XITEM,
  'menu.avizoView.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

MERGE INTO SC_MENUITEM A USING
 (SELECT
  84 as ID,
  1 as VERSION,
  'adminaviz' as CREATED_BY,
  TO_TIMESTAMP('17.12.2018 10:02:00.572000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as DATE_CREATED,
  'RequestLog' as GRIDDS,
  NULL as ICON_CLS,
  0 as IS_OPEN,
  TO_TIMESTAMP('17.12.2018 15:48:34.331000','fmDDfm.fmMMfm.YYYY fmHH24fm:MI:SS.FF') as LAST_UPDATED,
  'ROLE_AVADM' as NEEDROLE,
  81 as XITEM,
  'menu.avizoReqLog.title' as TITLE,
  'adminaviz' as UPDATED_BY,
  NULL as URI
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, VERSION, CREATED_BY, DATE_CREATED, GRIDDS, 
  ICON_CLS, IS_OPEN, LAST_UPDATED, NEEDROLE, XITEM, 
  TITLE, UPDATED_BY, URI)
VALUES (
  B.ID, B.VERSION, B.CREATED_BY, B.DATE_CREATED, B.GRIDDS, 
  B.ICON_CLS, B.IS_OPEN, B.LAST_UPDATED, B.NEEDROLE, B.XITEM, 
  B.TITLE, B.UPDATED_BY, B.URI)
WHEN MATCHED THEN
UPDATE SET 
  A.VERSION = B.VERSION,
  A.CREATED_BY = B.CREATED_BY,
  A.DATE_CREATED = B.DATE_CREATED,
  A.GRIDDS = B.GRIDDS,
  A.ICON_CLS = B.ICON_CLS,
  A.IS_OPEN = B.IS_OPEN,
  A.LAST_UPDATED = B.LAST_UPDATED,
  A.NEEDROLE = B.NEEDROLE,
  A.XITEM = B.XITEM,
  A.TITLE = B.TITLE,
  A.UPDATED_BY = B.UPDATED_BY,
  A.URI = B.URI;

COMMIT;
